version: '2'
services:
  web:
    image: kuklinistvan/calendar_solution-web:latest
    environment:
      - AGENDAV_ENVIRONMENT=dev
    volumes:
      - ./cs-web-config/davical:/usr/share/davical/config
      - ./cs-web-config/agendav:/usr/share/agendav/web/config
      - ./cs-web-config/infcloud:/usr/share/infcloud/external-config
      - ./bootstrap/web.sh:/bootstrap.sh
    ports:
      - 127.0.0.1:5020:80

  postgres:
    image: kuklinistvan/calendar_solution-postgres:latest
    volumes:
      - /var/lib/postgresql/data/pgdata
      - ./bootstrap/postgres.sh:/bootstrap.sh
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata

  mariadb:
    image: mariadb:10.3.22
    volumes:
      - ./bootstrap/mariadb.sh:/bootstrap.sh
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword

